import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import LandingPage from "../components/LandingPage/Index";
import axios from "axios";

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{data?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LandingPage />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps() {
  const number = Math.floor(Math.random() * 10);
  const res = await axios("https://fakestoreapi.com/products/" + number);
  const data = res.data;
  return {
    props: {
      data,
    },
    revalidate: 10,
  };
}
